version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT:-80}:80"
    depends_on:
      - application

  application:
    build: docker/application
    working_dir: /application
    volumes:
      - .:/application:Z
      - './docker/application/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    working_dir: /application
    volumes:
      - .:/application
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/alternatives/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=wst_db
      - MYSQL_USER=wst
      - MYSQL_PASSWORD=pwd
    ports:
      - '${DB_PORT:-3306}:3306'
